kind: Deployment
apiVersion: apps/v1
metadata:
  name: guacd
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/guacd
  uid: 966cecc1-6098-4fe1-9735-cacc9ec2f0b0
  resourceVersion: '496730'
  generation: 2
  creationTimestamp: '2020-07-05T15:59:04Z'
  labels:
    app: guacd
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"guacd"},"name":"guacd","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"guacd"}},"template":{"metadata":{"labels":{"name":"guacd"}},"spec":{"containers":[{"env":[{"name":"GUACD_LOG_LEVEL","value":"debug"}],"image":"guacamole/guacd","name":"guacd","resources":{"requests":{"cpu":"200m","memory":"400Mi"}}}]}}}}
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2020-07-07T12:18:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:name': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:name': {}
            'f:spec':
              'f:containers':
                'k:{"name":"guacd"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"GUACD_LOG_LEVEL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources':
                    .: {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
        'f:status':
          'f:collisionCount': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2020-07-08T11:52:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guacd
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: guacd
    spec:
      containers:
        - name: guacd
          image: sergeyfilyanin/guacd
          env:
            - name: GUACD_LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-07-07T12:18:51Z'
      lastTransitionTime: '2020-07-05T15:59:04Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "guacd-86c9c8f7b" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-07-08T11:52:26Z'
      lastTransitionTime: '2020-07-08T11:52:26Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
