kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: default
  selfLink: /api/v1/namespaces/default/services/postgres
  uid: 9c32a225-ec51-4ecf-b47b-444501878bb8
  resourceVersion: '5289'
  creationTimestamp: '2020-07-05T15:31:29Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres","namespace":"default"},"spec":{"ports":[{"name":"pgql","nodePort":31222,"port":5432,"protocol":"TCP","targetPort":5432}],"selector":{"app":"postgres"},"type":"NodePort"}}
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2020-07-05T15:31:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:clusterIP': {}
          'f:externalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":5432,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:nodePort': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:app': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  ports:
    - name: pgql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31222
  selector:
    app: postgres
  clusterIP: 10.100.238.11
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
